---
version: "2"

services:
  chromium:
    container_name: restockbot-chromium
    image: montferret/chromium
    ports:
      - "9222:9222"
    restart: always
  postgres:
    container_name: restockbot-postgres
    env_file:
      - ./docker/environment
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-storage:
    driver: local
